import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { resolve } from 'node:path';
import { createUiServer, builtHtml } from './ui-server';
import { FileStore } from './store';
import { acquireOwner } from './owner';
const path = process.env.REFERENCE_UI_DATA ?? resolve('.data/preferences.json');
const release = acquireOwner(path);
const server = createUiServer(builtHtml(), new FileStore(path, { compact: false }));
server.server.onclose = release;
process.once('exit', release);
for (const signal of ['SIGINT', 'SIGTERM'] as const) process.on(signal, () => { void server.close().then(() => { release(); process.exit(0); }); });
await server.connect(new StdioServerTransport());
