import { mkdir, writeFile } from 'node:fs/promises';
const html = await Bun.file('apps/mcp-ui/dist/index.html').text();
if (/<script[^>]+src=|<link[^>]+rel=["']stylesheet/.test(html))
  throw new Error('MCP UI must be a self-contained HTML resource.');
await mkdir('packages/backend/convex/generated', { recursive: true });
await writeFile(
  'packages/backend/convex/generated/mcp_ui.ts',
  `// Generated by build:mcp-ui; never edit.\nexport const mcpUiHtml = ${JSON.stringify(html)};\n`,
);
console.log('Embedded self-contained MCP UI for the Convex resource server.');
